//! Plain-language report summaries, newest first, with original paths and hashes.

pub struct Ruling {
    pub date: &'static str,
    pub kind: &'static str,
    pub title: &'static str,
    pub result: &'static str,
    pub path: &'static str,
    /// SHA-256 of the exact file named in path.
    pub hash: Option<&'static str>,
}

pub const RULINGS: &[Ruling] = &[
    Ruling {
        date: "2026-09-11",
        kind: "Research paper",
        title: "Research paper and supporting data",
        result: "The paper draws on our existing experiments to examine where performance improved, where tests failed and which questions remain open. We provide supporting data and analysis files so readers can review the evidence behind these findings.",
        path: "docs/papers/dynamical-synthesis/manuscript.tex",
        hash: None,
    },
    Ruling {
        date: "2026-09-07",
        kind: "Incomplete study",
        title: "Preparation for the learning comparison",
        result: "The latest round collected 175 of 336 planned measurements, while two earlier rounds collected all their data but found too few suitable questions. The main comparison is unfinished, so we cannot tell whether the approach improves learning.",
        path: "Loopseed-decisive-v15-exec/data/fish/experiments/decisive-2026-09-07T004253Z/USER-PAUSE.json",
        hash: Some("71ae880d2f5e5f742de32e65fa5ffed316a14d5d76bc38fb1fa2e66463645c42"),
    },
    Ruling {
        date: "2026-09-07",
        kind: "Completed comparison",
        title: "Performance after further training",
        result: "Prediction scores worsened on new and earlier test examples. Across 42 questions tested twice, 12 answers improved, 17 worsened and 55 stayed the same. Seven losses involved earlier skills, and neither update was adopted.",
        path: "fish/album/2026-09-07T0335-EAT-private-continuing-learning-result.md",
        hash: Some("a5873eeea7cb3898ea55dc1fa9e0c0f38ef6205b16fc7f4d55ed52ed90a9d9b1"),
    },
    Ruling {
        date: "2026-09-07",
        kind: "Study plan",
        title: "Separate prediction and response updates",
        result: "The plan called for separate prediction and answer updates on a copy of the system, reusing earlier examples. Test examples would stay out of training, and updates would need to pass checks for improvement and preserving earlier skills before adoption.",
        path: "fish/album/2026-09-07T0048-EAT-private-continuing-learning.md",
        hash: None,
    },
    Ruling {
        date: "2026-09-06",
        kind: "Study preparation",
        title: "Selecting study questions",
        result: "The plan would first look for questions that produced consistent results before training, then divide them into training and test sets. This report describes how questions would be chosen; later reports give the results.",
        path: "fish/album/2026-09-06T2328-EAT-decisive-eligibility-search.md",
        hash: None,
    },
    Ruling {
        date: "2026-09-06",
        kind: "Incomplete comparison",
        title: "Rule correction with feedback",
        result: "All 70 planned requests finished; two replies hit the length limit. Records showed a correct rule and successful reuse in one of six worlds with checked feedback, none with self-checking and two with supplied rules. No wrong initial rule was corrected, and conflicting records prevented a final decision. An earlier unscored request is reported separately.",
        path: "data/fish/labs/decisive-repair-context-2026-09-06T035210Z/descriptive-reconciliation.json",
        hash: Some("db0ad728179d10d623ae5d6c190e41255a60fe4219e21345bf57a307c09100ce"),
    },
    Ruling {
        date: "2026-09-06",
        kind: "Completed comparison",
        title: "Learning and reusing hidden rules",
        result: "The system identified 2 of 6 hidden rules correctly and gave 3 correct answers across 12 later questions using its saved rules. It did not pass the full learning and reuse test, which kept model weights fixed and supplied the saved rules in the prompt.",
        path: "data/fish/labs/decisive-acquisition-2026-09-05T221330Z/verdict.json",
        hash: Some("66e4deff6cc0f03675e6d6d515177f2e8b585a0b30505750d79eb0f4dee25565"),
    },
    Ruling {
        date: "2026-09-06",
        kind: "Diagnostic comparison",
        title: "Reasoning settings with supplied rules",
        result: "With rules provided for 12 questions, the prediction adapter scored 9 with extra reasoning and 2 without it; the answer adapter scored 7 and 2. Extra reasoning also required more generated text. The study tested use of given rules, without measuring rule discovery.",
        path: "data/fish/labs/decisive-ruleuse-2026-09-05T213200Z/verdict.json",
        hash: Some("380f9d1a09ed8f28b463b356860966f99494a54886c60a8907e2d1aa2005eca4"),
    },
    Ruling {
        date: "2026-09-05",
        kind: "Diagnostic comparison",
        title: "Structured and direct answers",
        result: "On 8 selected questions, the trained adapter passed 4 with forced output formatting and 4 without it; a control trained with mismatched answers passed none. Direct numerical answers scored 3 and 2 respectively. Structured replies used the checker for arithmetic, so the comparison changed both format and calculation support.",
        path: "fish/album/2026-09-05T2123-EAT-formal-interface-result.md",
        hash: Some("910206fe01a10274710c4b1eb4a27e0de33604e081a3983e13454d365805059c"),
    },
    Ruling {
        date: "2026-09-05",
        kind: "Incomplete study",
        title: "Initial tests of rule learning",
        result: "Across 8 simulated worlds, no initial rule was correct and one became correct after feedback. Using its own records, the system passed none of 16 later test sequences; with the original observations, it passed one. These results did not meet the requirements for starting the planned delayed test.",
        path: "data/fish/labs/decisive-worlds-2026-09-05T192730Z/verdict.json",
        hash: Some("91f3b3081242903ae42d517be8f32cbe270f846cdeb90eb7c35f9d3e4e7a2cfe"),
    },
    Ruling {
        date: "2026-09-05",
        kind: "Completed comparison",
        title: "Harder mathematics comparison",
        result: "Each model answered 27 problems three times. The trained adapter and a control trained with mismatched answers each passed 2 of 81 replies; the earlier prediction adapter passed 3. The study did not show a gain over the control. Difficulty and answer requirements both changed from the earlier study, so the cause of the difference remains unclear.",
        path: "fish/album/2026-09-05T1630-EAT-formal-speaking-result.md",
        hash: Some("c5458f1ae6126b39b9856e7612be5ecbf0bd88dd22f9a5cae4c4529334dc744e"),
    },
    Ruling {
        date: "2026-09-04",
        kind: "Completed comparison",
        title: "Training on familiar problem types",
        result: "The trained adapter passed 43 of 64 questions with new numbers in 16 problem types used in training, while the base model and a control trained with mismatched answers passed none. Accepted answers passed exact mathematical checks and a separate AI review, but the finding remains limited to these problem types and conditions.",
        path: "fish/album/2026-09-04T0043-EAT-clean-formal-claim-transfer.md",
        hash: Some("5a175b2a2fdd8638f0aeadf221faea2d4d42631ddb92740b4605fbef01d57a03"),
    },
    Ruling {
        date: "2026-09-03",
        kind: "Diagnostic comparison",
        title: "Place-value tests with revised prompts",
        result: "The new adapter passed all 18 questions after training prompts were rebuilt from the problem definitions, while the base model and earlier adapter passed none. Its replies contained no unrelated numbers, and the exact mathematical checks supported a larger comparison.",
        path: "fish/album/2026-09-03T1945-EAT-clean-claim-safety.md",
        hash: Some("b6cd897a2e2097f2418ce4a570a516aacf9beab8ee0bdb9771f3d874d356b3d6"),
    },
    Ruling {
        date: "2026-09-03",
        kind: "Completed comparison",
        title: "Answers without supplied calculation steps",
        result: "Without supplied calculation steps, the trained adapter passed 25 of 64 questions; the base model and a control trained with mismatched answers passed none. Negative constants appeared in 3 of its 39 failed replies, exceeding the study’s 2% limit. Numbers copied from earlier corrections were investigated as a possible cause.",
        path: "fish/album/2026-09-03T1908-EAT-formal-claim-transfer-stage1.md",
        hash: Some("78edb2f6ec08ad6ec6c1ee030b263b8318714a2d83c7275c5d63b2fa328fc71d"),
    },
    Ruling {
        date: "2026-09-03",
        kind: "Completed comparison",
        title: "Training with supplied calculation steps",
        result: "With calculation steps provided, the trained adapter passed 94 of 128 questions, compared with 73 for the base model and 52 for the prediction adapter. It gained 21 correct answers and lost none against the base model, but one reply failed the check on negative constants, preventing a full pass.",
        path: "fish/album/2026-09-03T0028-EAT-claim-coat-primary-ruling.md",
        hash: Some("cb775d4ba37fb2a3080b4c30560cdc6bffbb07ad27f0e311448b48e12d355a03"),
    },
    Ruling {
        date: "2026-08-16",
        kind: "Evaluation and activation",
        title: "Prediction update results",
        result: "Prediction loss fell from 2.552 to 1.999 on the same 17 examples kept out of training, with improvements in all 9 teaching groups. The update passed its checks and was adopted for prediction only; the test did not measure better answers.",
        path: "fish/album/2026-08-16T1950-EAT-prediction-coat-promotion-ruling.md",
        hash: Some("1d257d886768fbcd501f73ab047b46d45e6a6439370042c99c356e412302fd65"),
    },
    Ruling {
        date: "2026-08-14",
        kind: "Completed comparison",
        title: "Memory retrieval in system tests",
        result: "All 396 requests finished, but the system retrieved no memories even when retrieval was enabled. The study could not test the benefit of memory retrieval, and checks confirmed that the source database remained unchanged.",
        path: "fish/album/2026-08-14T074428-EAT-body-evolution.md",
        hash: None,
    },
    Ruling {
        date: "2026-08-14",
        kind: "Component evaluations",
        title: "Tool use and image display",
        result: "The record reports successful tool activation on 19 of 20 requests and image display in 4 initial and 4 later tests. A separate comparison covered 3 models, while checks of state tracking, memory references and whether the results could be repeated remained open.",
        path: "docs/ROADMAP.md",
        hash: None,
    },
    Ruling {
        date: "2026-08-12",
        kind: "Observation",
        title: "Word overlap between inputs and replies",
        result: "A score based on shared words rose from 0.0244 at 8 input cycles to 0.0762 at 63, then fell to 0.0712 at 128. It compares original input–reply matches with replies assigned to other inputs, without showing understanding or learning. Later changes started a separate measurement period.",
        path: "docs/ROADMAP.md",
        hash: None,
    },
    Ruling {
        date: "2026-08-05",
        kind: "Interaction record",
        title: "Memory use in guest exchanges",
        result: "About 295 exchanges with a guest were recorded with a human supervisor present. The report shows examples of retrieved memories used in reasoning, but does not provide a controlled test of whether learning improved.",
        path: "fish/album/2026-08-05-the-second-visit.md",
        hash: None,
    },
    Ruling {
        date: "2026-08-04",
        kind: "Exploratory comparison",
        title: "Base model and full system",
        result: "The base model and full system were compared using the same model weights, server and settings for generating replies. The full system added a system prompt, memory and prediction together, so the comparison could not show how much each part contributed.",
        path: "fish/album/2026-08-04-bare-water-control.md",
        hash: None,
    },
    Ruling {
        date: "2026-08-04",
        kind: "Observation",
        title: "Prediction error across early sessions",
        result: "Across sessions with one participant, median prediction error fell from 0.479 to 0.369 and then stayed near 0.40. The ±0.03 band shows observed variation, not a confidence interval, and these records do not show whether training caused the change.",
        path: "fish/album/2026-08-04-the-plateau-era-close.png",
        hash: None,
    },
    Ruling {
        date: "2026-08-03",
        kind: "Observation",
        title: "Prediction error over one day",
        result: "On the first full day, median prediction error fell from 0.48 to 0.34 by afternoon. Because topics, context and the participant’s messages were not kept fixed, this change does not by itself show learning.",
        path: "fish/album/2026-08-03-the-first-fall.png",
        hash: None,
    },
];
